    1  Data Import
    2  Data Preprocessing
    3  Feature Engineering
    4  Feature Selection
    5  Model Architecture
    6  Model Training
    7  Model Evaluation
    7.1  Accuracy & Loss
    7.2  Error Analysis
    8  Model Application
    8.1  Test Predictions
    8.2  Custom Reviews

In [1]:
import pandas as pd
import os

In [2]:
path = "./data_movie_reviews/"
positiveFiles = [x for x in os.listdir(path+"train/pos/") if x.endswith(".txt")]
negativeFiles = [x for x in os.listdir(path+"train/neg/") if x.endswith(".txt")]
# testFiles = [x for x in os.listdir(path+"test/") if x.endswith(".txt")]

In [3]:
positiveFiles

['0_9.txt',
 '10000_8.txt',
 '10001_10.txt',
 '10002_7.txt',
 '10003_8.txt',
 '10004_8.txt',
 '10005_7.txt',
 '10006_7.txt',
 '10007_7.txt',
 '10008_7.txt',
 '10009_9.txt',
 '1000_8.txt',
 '10010_7.txt',
 '10011_9.txt',
 '10012_8.txt',
 '10013_7.txt',
 '10014_8.txt',
 '10015_8.txt',
 '10016_8.txt',
 '10017_9.txt',
 '10018_8.txt',
 '10019_8.txt',
 '1001_8.txt',
 '10020_8.txt',
 '10021_8.txt',
 '10022_7.txt',
 '10023_9.txt',
 '10024_9.txt',
 '10025_9.txt',
 '10026_7.txt',
 '10027_7.txt',
 '10028_10.txt',
 '10029_10.txt',
 '1002_7.txt',
 '10030_10.txt',
 '10031_10.txt',
 '10032_10.txt',
 '10033_10.txt',
 '10034_8.txt',
 '10035_9.txt',
 '10036_8.txt',
 '10037_9.txt',
 '10038_10.txt',
 '10039_10.txt',
 '1003_10.txt',
 '10040_10.txt',
 '10041_10.txt',
 '10042_10.txt',
 '10043_10.txt',
 '10044_9.txt',
 '10045_10.txt',
 '10046_9.txt',
 '10047_10.txt',
 '10048_10.txt',
 '10049_8.txt',
 '1004_7.txt',
 '10050_10.txt',
 '10051_10.txt',
 '10052_10.txt',
 '10053_8.txt',
 '10054_10.txt',
 '10055_7.tx

In [3]:
test_positiveFiles = [x for x in os.listdir(path+"test/pos/") if x.endswith(".txt")]
test_negativeFiles = [x for x in os.listdir(path+"test/neg/") if x.endswith(".txt")]
# test_testFiles = [x for x in os.listdir(path+"test/") if x.endswith(".txt")]

In [4]:
positiveReviews, negativeReviews, testReviews = [], [], []
for pfile in positiveFiles:
    with open(path+"train/pos/"+pfile, encoding="latin1") as f:
        positiveReviews.append(f.read())
for nfile in negativeFiles:
    with open(path+"train/neg/"+nfile, encoding="latin1") as f:
        negativeReviews.append(f.read())
# for tfile in testFiles:
#     with open(path+"test/"+tfile, encoding="latin1") as f:
#         testReviews.append(f.read())

In [5]:
# positiveReviews, negativeReviews, testReviews = [], [], []
# for pfile in positiveFiles:
#     with open(path+"train/pos/"+pfile, encoding="latin1") as f:
#         positiveReviews.append(f.read())
# for nfile in negativeFiles:
#     with open(path+"train/neg/"+nfile, encoding="latin1") as f:
#         negativeReviews.append(f.read())
# for tfile in testFiles:
#     with open(path+"test/"+tfile, encoding="latin1") as f:
#         testReviews.append(f.read())

In [6]:
test_positiveReviews, test_negativeReviews, test_testReviews = [], [], []
for pfile in test_positiveFiles:
    with open(path+"test/pos/"+pfile, encoding="latin1") as f:
        test_positiveReviews.append(f.read())
for nfile in test_negativeFiles:
    with open(path+"test/neg/"+nfile, encoding="latin1") as f:
        test_negativeReviews.append(f.read())
# for tfile in test_testFiles:
#     with open(path+"test/"+tfile, encoding="latin1") as f:
#         testReviews.append(f.read())

In [7]:
# reviews = pd.concat([
#     pd.DataFrame({"review":positiveReviews, "label":1, "file":positiveFiles}),
#     pd.DataFrame({"review":negativeReviews, "label":0, "file":negativeFiles}),
#     pd.DataFrame({"review":testReviews, "label":-1, "file":testFiles})
# ], ignore_index=True).sample(frac=1, random_state=1)
# reviews.head()

In [8]:
reviews = pd.concat([
    pd.DataFrame({"review":positiveReviews, "label":1, "file":positiveFiles}),
    pd.DataFrame({"review":negativeReviews, "label":0, "file":negativeFiles}),
    pd.DataFrame({"review":test_positiveReviews, "label":1, "file":test_positiveFiles}),
    pd.DataFrame({"review":test_negativeReviews, "label":0, "file":test_negativeFiles})
], ignore_index=True).sample(frac=1, random_state=1)
    reviews.head()

file  label                                             review
26247  11122_8.txt      1  Fame is one of the best movies I've seen about...
35067  7811_10.txt      1  This movie fully deserves to be one of the top...
34590  7382_10.txt      1  in a time of predictable movies, in which abou...
16668   2501_1.txt      0  I saw this on TV the other nightÂ
 or rather I...
12196   9728_7.txt      1  I am a huge fan of Simon Pegg and have watched...

In [9]:
reviews.shape

(50000, 3)

In [10]:
# test_reviews = pd.concat([
#     pd.DataFrame({"review":test_positiveReviews, "label":1, "file":test_positiveFiles}),
#     pd.DataFrame({"review":test_negativeReviews, "label":0, "file":test_negativeFiles})
# ], ignore_index=True).sample(frac=1, random_state=1)
# test_reviews.head()

### Feature engineering

Text preprocessing, tokenizing and filtering of stopwords are included in a high level component that is able to build a dictionary of features and transform documents to feature vectors.

We remove the stop words in order to improve the analytics

In [11]:
from sklearn import feature_extraction
import numpy as np

In [ ]:
    print "Creating the bag of words...\n"
    from sklearn.feature_extraction.text import CountVectorizer

    # Initialize the "CountVectorizer" object, which is scikit-learn's
    # bag of words tool.  
    vectorizer = CountVectorizer(analyzer = "word",   \
                                 tokenizer = None,    \
                                 preprocessor = None, \
                                 stop_words = None,   \
                                 max_features = 5000) 


    # fit_transform() does two functions: First, it fits the model
    # and learns the vocabulary; second, it transforms our training data
    # into feature vectors. The input to fit_transform should be a list of 
    # strings.
    train_data_features = vectorizer.fit_transform(clean_train_reviews)

    # Numpy arrays are easy to work with, so convert the result to an 
    # array
    train_data_features = train_data_features.toarray()

In [12]:
f = feature_extraction.text.CountVectorizer(stop_words = 'english', ngram_range=(2, 2),max_features=5000 )
X = f.fit_transform(reviews["review"])


In [13]:
np.shape(X)

(50000, 5000)

In [120]:
# f.get_feature_names()

In [14]:
y = reviews['label']

In [15]:
X.shape

(50000, 5000)

In [16]:
y.shape

(50000,)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


In [19]:
print([np.shape(X_train), np.shape(X_test)])

[(25000, 5000), (25000, 5000)]


In [20]:
y_train.shape, y_test.shape

((25000,), (25000,))

In [21]:
from sklearn.naive_bayes import MultinomialNB 
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [22]:
model.predict(X_train)

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [23]:
model.score(X_train, y_train)

0.83008000000000004

In [24]:
model.predict(X_test)

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [25]:
model.score(X_test, y_test)

0.81072

## Testing Data

In [133]:
from sklearn import metrics

In [134]:
list_alpha = np.arange(1/100000, 20, 0.11)
score_train = np.zeros(len(list_alpha))
score_test = np.zeros(len(list_alpha))
recall_test = np.zeros(len(list_alpha))
precision_test= np.zeros(len(list_alpha))
count = 0
for alpha in list_alpha:
    bayes = MultinomialNB(alpha=alpha)
    bayes.fit(X_train, y_train)
    score_train[count] = bayes.score(X_train, y_train)
    score_test[count]= bayes.score(X_test, y_test)
    recall_test[count] = metrics.recall_score(y_test, bayes.predict(X_test))
    precision_test[count] = metrics.precision_score(y_test, bayes.predict(X_test))
    count = count + 1 

In [135]:
matrix = np.matrix(np.c_[list_alpha, score_train, score_test, recall_test, precision_test])
models = pd.DataFrame(data = matrix, columns = 
             ['alpha', 'Train Accuracy', 'Test Accuracy', 'Test Recall', 'Test Precision'])
models.head(n=10)

alpha  Train Accuracy  Test Accuracy  Test Recall  Test Precision
0  0.00001         0.85236        0.84776     0.847140        0.849305
1  0.11001         0.85232        0.84784     0.847220        0.849385
2  0.22001         0.85228        0.84784     0.847140        0.849441
3  0.33001         0.85220        0.84796     0.847300        0.849533
4  0.44001         0.85212        0.84800     0.847300        0.849601
5  0.55001         0.85220        0.84800     0.847220        0.849656
6  0.66001         0.85220        0.84800     0.847140        0.849712
7  0.77001         0.85208        0.84796     0.846981        0.849756
8  0.88001         0.85212        0.84792     0.846901        0.849744
9  0.99001         0.85220        0.84788     0.846822        0.849732

Lets select the model with the most test precision

In [136]:
best_index = models['Test Precision'].idxmax()
models.iloc[best_index, :]

alpha             19.910010
Train Accuracy     0.851280
Test Accuracy      0.846760
Test Recall        0.836785
Test Precision     0.854969
Name: 181, dtype: float64

In [137]:
m_confusion_test = metrics.confusion_matrix(y_test, bayes.predict(X_test))
m_confusion_test

array([[10664,  1782],
       [ 2049, 10505]], dtype=int64)

In [138]:
pd.DataFrame(data = m_confusion_test, columns = ['Predicted 0', 'Predicted 1'],
            index = ['Actual 0', 'Actual 1'])

Predicted 0  Predicted 1
Actual 0        10664         1782
Actual 1         2049        10505